#!/bin/bash
set -eo pipefail

if [ -z "${BOOST_VERSION}" ] ; then
    exit 0
fi

if [ -z "${DOCUMENT_ROOT}" ] ; then
    echo >&2 "DOCUMENT_ROOT is not set! (this is required for the Bitpoke Boost image)"
    exit 1
fi

set -u

echo >&2 "Bitpoke Boost detected, version: ${BOOST_VERSION}"

uid="$(id -u)"
gid="$(id -g)"

user="${WORKER_USER:-www-data}"
group="${WORKER_GROUP:-www-data}"

if [ ! -d "/usr/src/wordpress/wp-content" ] ; then
    echo >&2 "No WordPress source content found in /usr/src/wordpress, skipping initialization."
    exit 0
fi

if [ -e "${DOCUMENT_ROOT}/wp-content" ] && [ -n "$(find "${DOCUMENT_ROOT}/wp-content" -mindepth 1 -maxdepth 1 ! -name 'uploads' ! -name 'lost+found' -print -quit)" ]; then
    echo >&2 "WordPress content exists in '${DOCUMENT_ROOT}/wp-content', skipping initialization."
    exit 0
fi

if [ ! -d "${DOCUMENT_ROOT}/wp-content" ] ; then
    echo >&2 "Creating '${DOCUMENT_ROOT}/wp-content' directory."
    mkdir -p "${DOCUMENT_ROOT}/wp-content"
fi

# Copy all visible and hidden files without touching the dest root directory
shopt -s dotglob nullglob
cp -dR --preserve=mode /usr/src/wordpress/wp-content/* "${DOCUMENT_ROOT}/wp-content/"
shopt -u dotglob nullglob

if [ ! -d "${DOCUMENT_ROOT}/wp-content/plugins" ] ; then
    echo >&2 "Creating '${DOCUMENT_ROOT}/wp-content/plugins' directory."
    mkdir -p "${DOCUMENT_ROOT}/wp-content/plugins"
fi

if [ ! -d "${DOCUMENT_ROOT}/wp-content/themes" ] ; then
    echo >&2 "Creating '${DOCUMENT_ROOT}/wp-content/themes' directory."
    mkdir -p "${DOCUMENT_ROOT}/wp-content/themes"
fi

if [ "${uid}" -eq 0 ] ; then
    echo >&2 "Setting ownership of '${DOCUMENT_ROOT}/wp-content' to ${user}:${group}."
    chown -R "${user}:${group}" "${DOCUMENT_ROOT}/wp-content"
fi

echo >&2 "Complete! WordPress content has been successfully copied to '${DOCUMENT_ROOT}/wp-content'."
