#!/bin/bash
set -eo pipefail

if [ -z "${BOOST_VERSION}" ] ; then
    exit 0
fi

if [ -z "${DOCUMENT_ROOT}" ] ; then
    DOCUMENT_ROOT="${DOCUMENT_ROOT}"
fi

set -u

echo >&2 "Bitpoke Boost detected, version: ${BOOST_VERSION}"

uid="$(id -u)"
gid="$(id -g)"

user="${WORKER_USER:-www-data}"
group="${WORKER_GROUP:-www-data}"

if [ ! -e ${DOCUMENT_ROOT}/wp-content/mu-plugins/stack-mu-plugin ] && [ ! -e ${DOCUMENT_ROOT}/wp-content/mu-plugins/stack-mu-plugin/000-stack-mu-plugin.php ]; then
    echo >&2 "Installing Bitpoke Stack mu-plugin..."
    test -d ${DOCUMENT_ROOT}/wp-content/mu-plugins || mkdir -p ${DOCUMENT_ROOT}/wp-content/mu-plugins && chown "$user:$group" ${DOCUMENT_ROOT}/wp-content/mu-plugins
    cp -r /usr/src/stack-mu-plugin ${DOCUMENT_ROOT}/wp-content/mu-plugins/stack-mu-plugin
    chown -R "$user:$group" ${DOCUMENT_ROOT}/wp-content/mu-plugins/stack-mu-plugin
    cd ${DOCUMENT_ROOT}/wp-content/mu-plugins
    ln -sf stack-mu-plugin/stack-mu-plugin.php ${DOCUMENT_ROOT}/000-stack-mu-plugin.php
    chown "$user:$group" ${DOCUMENT_ROOT}/wp-content/mu-plugins/000-stack-mu-plugin.php
fi
