---
kind: pipeline
name: php-runtime-8.3

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C php pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C php $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C php test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C php push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: php-runtime-8.2

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C php pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C php $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C php test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C php push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: php-runtime-8.1

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C php pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C php $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C php test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C php push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: php-runtime-7.4

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C php pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C php $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C php test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C php push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""

---
kind: pipeline
name: wordpress-runtime-bedrock

depends_on:
  - php-runtime-8.2

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""

---
kind: pipeline
name: wordpress-runtime-bedrock-php-8.3

depends_on:
  - php-runtime-8.3

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""

---
kind: pipeline
name: wordpress-runtime-bedrock-php-8.1

depends_on:
  - php-runtime-8.1

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""

---
kind: pipeline
name: wordpress-runtime-bedrock-php-7.4

depends_on:
  - php-runtime-7.4

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.7

depends_on:
  - wordpress-runtime-bedrock

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.7-php-8.3

depends_on:
  - wordpress-runtime-bedrock-php-8.3

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.7-php-8.1

depends_on:
  - wordpress-runtime-bedrock-php-8.1

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.7-php-7.4

depends_on:
  - wordpress-runtime-bedrock-php-7.4

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.6

depends_on:
  - wordpress-runtime-bedrock

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.6-php-8.3

depends_on:
  - wordpress-runtime-bedrock-php-8.3

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.6-php-8.1

depends_on:
  - wordpress-runtime-bedrock-php-8.1

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
---
kind: pipeline
name: wordpress-runtime-6.6-php-7.4

depends_on:
  - wordpress-runtime-bedrock-php-7.4

workspace:
  base: /workspace
  path: src/github.com/bitpoke/stack-runtimes

steps:
  - &step
    name: setup docker
    pull: always
    image: docker.io/bitpoke/build:v0.8.0
    environment: &baseEnv
      TAG_SUFFIX: ${DRONE_BRANCH/master/}
      TEST_HOSTNAME: docker
      DOCKER_HOST: tcp://docker:2375
    commands:
      - dockerize -wait http://docker:2375/_ping -timeout 30s
      - docker info
      - make -C wordpress pull-$DRONE_STAGE_NAME

  - <<: *step
    name: build image
    pull: default
    commands:
      - make -C wordpress $DRONE_STAGE_NAME

  - <<: *step
    name: test image
    pull: default
    commands:
      - make -C wordpress test-$DRONE_STAGE_NAME

  - <<: *step
    name: publish
    pull: default
    environment:
      <<: *baseEnv
      DOCKER_USERNAME: bitpokebot
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - /usr/local/bin/setup-credentials-helper.sh
      - make -C wordpress push-$DRONE_STAGE_NAME

services:
  - name: docker
    image: docker:20.10.24-dind-rootless
    environment:
      DOCKER_TLS_CERTDIR: ""
