#!/usr/bin/env bash

# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o pipefail

PHP_VERSION="$1"

set -o nounset

if [ -z "${PHP_VERSION}" ] ; then
    echo "Usage: php-version PHP_VERSION" >&2
    exit 1
fi

IFS='.' read -ra VERSION_PARTS <<< "$PHP_VERSION"

if [ "${#VERSION_PARTS[@]}" -lt 3 ] ; then
    echo "Invalid version string ${PHP_VERSION}" >&2
    exit 2
fi

echo "${VERSION_PARTS[0]}.${VERSION_PARTS[1]}"
