#!/usr/bin/env php
<?php
/* Copyright 2019 The Kubernetes Authors.

  Licensed under the Apache License, Version 2.0 (the 'License');
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an 'AS IS' BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
 */

define( 'DEFAULT_SERIES', '7.3' );
define( 'WORDPRESS_PHP_SERIES', [
    '5.2' => '7.3',
    '5.1' => '7.2',
    '5.0' => '7.2',
    '4.9' => '7.2',
    '4.8' => '7.2',
] );

if ( count( $argv ) != 2 ) {
    fwrite(STDERR, 'Usage: wordpress-php-series WORDPRESS_VERSION\n');
    exit(1);
}

$wp_version = trim($argv[1]);

@list( $major, $minor, $patch, $tag ) = explode( '.', $wp_version, 4 );

echo @WORDPRESS_PHP_SERIES["$major.$minor"] ?: DEFAULT_SERIES;
