ARG BASE_IMAGE=docker.io/bitpoke/wordpress-runtime:bedrock-php-8.1
FROM ${BASE_IMAGE} as bedrock
ENV WORDPRESS_VERSION=6.3.3
ENV WP_CONTENT_DIR=${DOCUMENT_ROOT}/wp-content
ENV STACK_MEDIA_PATH=/wp-content/uploads
RUN set -ex \
    && wp core download --skip-content --path=web/wp --version=${WORDPRESS_VERSION} \
    && cp /usr/local/docker/webroot/* /app/web/
ONBUILD COPY --chown=www-data:www-data config /app/config
ONBUILD COPY --chown=www-data:www-data wp-content /app/web/wp-content
