ARG BASE_IMAGE=quay.io/presslabs/wordpress-runtime:bedrock
FROM ${BASE_IMAGE} as bedrock
WORKDIR /src

# Inject custom env vars as build args
ONBUILD ARG COMPOSER_AUTH
ONBUILD ENV COMPOSER_AUTH ${COMPOSER_AUTH}

# Install project dependencies as first build step for child images so that we
# heat up composer cache
ONBUILD COPY --chown=www-data:www-data composer.json composer.lock /src/
ONBUILD RUN COMPOSER_AUTH=${COMPOSER_AUTH} composer install --no-dev --no-interaction --no-progress --no-ansi --no-scripts

ONBUILD COPY --chown=www-data:www-data . /src
ONBUILD RUN COMPOSER_AUTH=${COMPOSER_AUTH} composer install --no-dev --no-interaction --no-progress --no-ansi --no-scripts
ONBUILD RUN cp -a /src/. /app
