ARG BASE_IMAGE=quay.io/presslabs/php-runtime:7.3-latest
FROM ${BASE_IMAGE}

ENV WP_CLI_VERSION=2.1.0

USER root

COPY docker/build-scripts /usr/local/docker/build-scripts/

RUN set -ex \
    && /usr/local/docker/build-scripts/install-wp-cli

COPY --chown=www-data:www-data ./docker /usr/local/docker

USER www-data
