ARG BASE_IMAGE=quay.io/presslabs/wordpress-runtime:bedrock-php-7.4
FROM ${BASE_IMAGE} as bedrock
ENV WORDPRESS_VERSION=5.6.4
ENV WP_CONTENT_DIR=${DOCUMENT_ROOT}/wp-content
ENV STACK_MEDIA_PATH=/wp-content/uploads
RUN set -ex \
    && wp core download --path=web/wp --version=${WORDPRESS_VERSION} \
    && cp /usr/local/docker/webroot/* /app/web/
ONBUILD COPY --chown=www-data:www-data config /app/config
ONBUILD COPY --chown=www-data:www-data wp-content /app/web/wp-content
