#!/bin/bash

# A shell script for installing rclone
set -eo pipefail

TMP="$(mktemp -d)"
cleanup() {
    rm -rf "${TMP}"
}
trap cleanup EXIT

RELEASE_URL="https://github.com/ncw/rclone/releases/download/v${RCLONE_VERSION}"
ZIP_FILE="rclone-v${RCLONE_VERSION}-linux-amd64.zip"
CHECKSUMS_FILE="SHA256SUMS"

set -x
curl -sL "${RELEASE_URL}/${CHECKSUMS_FILE}" -o "${TMP}/${CHECKSUMS_FILE}"
curl -sL "${RELEASE_URL}/${ZIP_FILE}" -o "${TMP}/${ZIP_FILE}"
cd "${TMP}"
sha256sum --ignore-missing -c "${CHECKSUMS_FILE}"
unzip "${ZIP_FILE}"
chmod +x "${TMP}/${ZIP_FILE}"
mv "${TMP}/$(basename "${ZIP_FILE}" .zip)/rclone" /usr/local/bin/rclone
