- name: pdo
- name: "exif"
- name: "gd"
  phpMaxVersion: 7.4
  build:
    args:
      - "--with-jpeg-dir=/usr/include/"
      - "--with-png-dir=/usr/include/"
      - "--with-webp-dir=/usr/include/"
    depends:
      - libjpeg62-turbo-dev
      - libpng-dev
      - libwebp-dev
- name: "gd"
  phpMinVersion: 7.4
  build:
    args:
      - "--with-jpeg=/usr/include/"
      - "--with-png=/usr/include/"
      - "--with-webp=/usr/include/"
    depends:
      - libjpeg62-turbo-dev
      - libpng-dev
      - libwebp-dev
- name: imap
  build:
    depends:
      - "libc-client-dev"
      - "libkrb5-dev"
    args:
      - "--with-kerberos"
      - "--with-imap-ssl"
- name: intl
  build:
    depends:
      - "libicu-dev"
      - "zlib1g-dev"
- name: gettext
- name: mysqli
- name: pdo_mysql
- name: opcache
- name: pcntl
- name: shmop
- name: tidy
  build:
    depends:
      - "libtidy-dev"
- name: simplexml
- name: xmlrpc
  type: pecl
- name: xsl
  build:
    depends:
      - "libxslt-dev"
- name: zip
  build:
    args:
      - "--with-libzip=/usr/include/"
    depends:
      - "libzip-dev"
      - "zlib1g-dev"

#
# PECL extensions
#

# Install mcrypt for backward compatibility
- name: mcrypt
  version: 1.0.3
  type: pecl
  build:
    depends:
      - "libmcrypt-dev"

# install apcu before serializers so that they detect and enable support for it
- name: apcu
  type: pecl
  version: 5.1.20
  priority: 30
- name: apc
  pecl_name: apcu_bc
  type: pecl
  version: 1.0.5

# install serializers to make them available for the rest of the extensions
- name: igbinary
  type: pecl
  version: 3.1.4
- name: msgpack
  type: pecl
  version: 2.1.1
- name: protobuf
  type: pecl
  version: 3.13.0
- name: zstd
  type: pecl
  version: 0.9.0
  build:
    depends:
      - "libzstd-dev"

- name: grpc
  type: pecl
  version: 1.31.0
#- name: imagick
#  type: pecl
#  version: 3.4.4
#  depends:
#    - ghostscript
#  build:
#    depends:
#      - "libmagickwand-dev"
- name: mailparse
  type: pecl
  version: 3.1.0
- name: memcached
  type: pecl
  version: 3.1.5
  build:
    depends:
      - "libmemcached-dev"
      - "zlib1g-dev"
    args:
      - "--enable-memcached-igbinary"
      - "--enable-memcached-msgpack"
      - "--enable-memcached-json"
- name: oauth
  type: pecl
  version: 2.0.5
  build:
    depends:
      - 'libpcre3-dev'
- name: redis
  type: pecl
  version: 5.3.4
  build:
    args:
      - "--enable-redis-igbinary"
      - "--enable-redis-msgpack"
      - "--enable-redis-lzf"
      - "--enable-redis-zstd"
